spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /**
server:
  port: 8080
## 日志设置
## 日志加载顺序logback.xml--->application.properties--->logback-spring.xml
logging:
  config: classpath:logback.xml
  path: "/logs"
  file: front.log
  level: debug
dist:
  server:
    prefix: http://127.0.0.1/
    secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzE3MjcyNjkxMzIsInBheWxvYWQiOiJcInhpYW9qaWFuZ1wiIn0.OhzV51QMAi2JreuarIvnd1yEZWJLty9f02pkiZjl7M8


