##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs/
  file: dist.log

