##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/authority?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
      filters: log4j,wall,mergeStat

#多数据源
biz:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/distribution?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: dist.log

---

